# Generated by Django 5.0.7 on 2024-08-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='endereço',
            new_name='endereco',
        ),
    ]
