# Generated by Django 5.0.7 on 2024-08-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_aluno_data_nascimento_aluno_email_aluno_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
