# Generated by Django 5.0.7 on 2024-09-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_aluno_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
