# Generated by Django 5.0.7 on 2024-09-04 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_administrador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'verbose_name': 'Administradore'},
        ),
    ]
