# Generated by Django 5.0.7 on 2024-09-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_alter_administrador_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
