# Generated by Django 5.0.7 on 2024-09-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_alter_administrador_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='data_cadastro',
            field=models.DateField(blank=True, null=True),
        ),
    ]
