# Generated by Django 5.0.7 on 2024-09-04 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_alter_administrador_data_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='data_cadastro',
        ),
    ]
