# Generated by Django 5.0.7 on 2024-08-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_usuarios_options_alter_usuarios_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='nome',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='senha',
            field=models.CharField(max_length=64),
        ),
    ]
